version: '3.4'
services:
  panorama_referal:
    container_name: panorama_referal
    build:
      context: ../..
      dockerfile: ${DOCKERFILE}
    volumes:
      - ../../src:/usr/project/src
    ports:
      - 80:${APP_PORT}
    networks:
      - panorama_net
networks:
  panorama_net:
    driver: bridge
