version: '3.4'
services:
  nginx:
    image: nginx:1.20-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    networks:
      - panorama_net
  certbot:
    image: certbot/certbot
  panorama_mongo:
    container_name: panorama_mongo
    image: mongo
    networks:
      - panorama_net
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - /var/data/db
      - ./mongo-config.sh:/docker-entrypoint-initdb.d/mongo-config.sh
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PSWD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
volumes:
  mongodb:
    driver: local
networks:
  panorama_net:
    driver: bridge
