version: '3.4'
services:
  app_mongo:
    container_name: panorama_mongo
    image: mongo
    networks:
      - panorama_net
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./mongo-config.sh:/docker-entrypoint-initdb.d/mongo-config.sh
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PSWD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
  app:
    container_name: app
    build:
      context: ../..
      dockerfile: ${DOCKERFILE}
    volumes:
      - ../../src:/usr/project/src
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - panorama_net
    depends_on:
      - app_mongo
networks:
  panorama_net:
    driver: bridge
